resolver: lts-9.1
packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: d347ccf3605d0851dd0f7046fe63f364510ef1a0
  extra-dep: true
extra-deps: 
- gamma-0.9.0.2
- permutation-0.5.0.5
- continued-fractions-0.9.1.1
- converge-0.1.0.1
- combinat-0.2.8.2

nix:
  shell-file: shell.nix
flags: {}
extra-package-dbs: []
